src/Entity/File.php
<?php


namespace App\Entity;

use App\Repository\FileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FileRepository::class)]
class File
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'files')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $size = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $last_action = null;

    #[ORM\Column(length: 255)]
    private ?string $owner = null;

    #[ORM\Column(length: 255)]
    private ?string $file = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): static
    {
        $this->size = $size;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getLastAction(): ?\DateTimeInterface
    {
        return $this->last_action;
    }

    public function setLastAction(\DateTimeInterface $last_action): static
    {
        $this->last_action = $last_action;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(string $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): static
    {
        $this->file = $file;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;
    
    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 15)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 100)]
    private ?string $adress = null;

    #[ORM\Column(length: 50)]
    private ?string $city = null;

    #[ORM\Column(length: 6)]
    private ?string $postal_code = null;

    #[ORM\Column]
    private ?float $used_space = 0;

    #[ORM\Column]
    private ?float $total_space = 0;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $verifToken ;

    #[ORM\OneToMany(mappedBy: 'user_id', targetEntity: File::class)]
    private Collection $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->first_name;
    }

    public function setFirstname(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->last_name;
    }

    public function setLastname(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->first_name .' '. $this->last_name;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getUsedSpace(): ?float
    {
        return $this->used_space;
    }

    public function setUsedSpace(float $used_space): static
    {
        $this->used_space = $used_space;

        return $this;
    }

    public function getTotalSpace(): ?float
    {
        return $this->total_space;
    }

    public function setTotalSpace(float $total_space): static
    {
        $this->total_space = $total_space;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getVerifToken(): ?string
    {
        return $this->verifToken;
    }

    public function setVerifToken(?string $verifToken): static
    {
        $this->verifToken = $verifToken;

        return $this;
    }

    /**
     * @return Collection<int, File>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): static
    {
        if (!$this->files->contains($file)) {
            $this->files->add($file);
            $file->setUser($this);
        }

        return $this;
    }

    public function removeFile(File $file): static
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getUser() === $this) {
                $file->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/FileController.php
<?php

namespace App\Controller;

use DateTime;
use SplFileInfo;
use App\Entity\File;
use App\Form\AddFileType;
use App\Repository\FileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Mime\FileinfoMimeTypeGuesser;
use Symfony\Component\HttpFoundation\BinaryFileResponse;




class FileController extends AbstractController
{
    //const BYTES_IN_ONE_GIGABYTE = 1.0e9; // 1 Go = 1 x 10^9 octets
    const BYTES_IN_ONE_GIGABYTE = 1024 * 1024 * 1024;
    #[Route('/file', name: 'app_file')]
    public function index(Request $request, EntityManagerInterface $entityManager, FileRepository $fileRepository): Response
    {
        $file = new File();
        $user = $this->getUser();
    
        $form = $this->createForm(AddFileType::class, $file);
        $form->handleRequest($request);
    
        $allFiles = $fileRepository->findBy(['user' => $this->getUser()]);
    
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['file']->getData();
    
            $originalFileName = $uploadedFile->getClientOriginalName();
            $fileSizeInBytes = $uploadedFile->getSize();
            $fileSizeInGigabytes = $fileSizeInBytes / self::BYTES_IN_ONE_GIGABYTE;
    
            // Vérification de l'espace total
            if (($user->getUsedSpace() + $fileSizeInGigabytes) > $user->getTotalSpace()) {
                $this->addFlash('error', 'Vous avez dépassé votre limite de stockage.');
                return $this->redirectToRoute('app_file');
            }

            // dd($user->getUsedSpace() + $fileSizeInGigabytes);
    
            $user->setUsedSpace($user->getUsedSpace() + $fileSizeInGigabytes);
            $entityManager->persist($user);
    
            $targetDirectory = $this->getParameter('upload_directory');
            $fileName = md5(uniqid()).'.'.$uploadedFile->guessExtension();
            $uploadedFile->move($targetDirectory, $fileName);
    
            $movedFile = new SplFileInfo($this->getParameter('upload_directory').'/'.$fileName);
    
            $file->setName($originalFileName);
            $file->setSize($movedFile->getSize());
            $file->setOwner($user->getEmail());
            $file->setDate(new DateTime());
            $file->setLastAction(new DateTime());
            $file->setFile($fileName);
            $file->setUser($this->getUser());
    
            try {
                $entityManager->persist($file);
                $entityManager->flush();
                $this->addFlash('success', 'Votre fichier a été téléchargé avec succès.');
            } catch (\Exception $e) {
                $this->addFlash('error', 'Une erreur est survenue lors du téléchargement du fichier.');
            }
    
            return $this->redirectToRoute('app_file');
        }
    
        return $this->render('file/index.html.twig', [
            'form' => $form->createView(),
            'files' => $allFiles,
        ]);
    }



    
    
    #[Route('/file/delete/{id}', name: 'file_delete', methods: ['POST'])]
    public function delete(int $id, FileRepository $fileRepository, EntityManagerInterface $entityManager): Response
    {
        $file = $fileRepository->find($id);
        $user = $this->getUser();
    
        if (!$file || $file->getUser() !== $user) {
            throw $this->createNotFoundException('Fichier introuvable ou vous n’avez pas le droit d’accéder à ce fichier.');
        }
    
        $fileSizeToRemove = $file->getSize();
    
        $updatedUsedSpace = max($user->getUsedSpace() - $fileSizeToRemove, 0);
        $user->setUsedSpace($updatedUsedSpace);
        $entityManager->persist($user);
    
        $fileSystem = new Filesystem();
        $targetDirectory = $this->getParameter('upload_directory');
        try {
            $fileSystem->remove($targetDirectory . '/' . $file->getFile());
        } catch (IOExceptionInterface $exception) {
            echo "Erreur lors de la suppression du fichier dans " . $exception->getPath();
        }
    
        $entityManager->remove($file);
        $entityManager->flush();
    
        $this->addFlash('success', 'Fichier supprimé avec succès.');
        return $this->redirectToRoute('app_file');
    }
    








#[Route('/file/download/{id}', name: 'file_download')]
public function download(int $id, FileRepository $fileRepository): Response
{
    $fileEntity = $fileRepository->find($id);
    if(!$fileEntity || $fileEntity->getUser() !== $this->getUser()) {
        throw $this->createNotFoundException('Fichier non trouvé ou accès non autorisé.');
    }

    $filePath = $this->getParameter('upload_directory').'/'.$fileEntity->getFile();
    
    return $this->file($filePath, $fileEntity->getName());
}





#[Route('/file/{filename}', name: 'app_file_serve')]
public function serveFile(string $filename): Response
{
    $file = $this->getParameter('upload_directory').'/'.$filename;

    if (!file_exists($file)) {
        throw $this->createNotFoundException('File not found.');
    }

    $response = new BinaryFileResponse($file);
    $response->headers->set('Content-Type', mime_content_type($file));
    $response->headers->set('Content-Disposition', 'inline; filename="'.basename($file).'"');

    return $response;
}






#[Route('/file/view/{id}', name: 'app_file_view')]
public function viewFile($id, FileRepository $fileRepository): Response
{
    $file = $fileRepository->find($id);
    
    if (!$file || $file->getUser() !== $this->getUser()) {
        throw $this->createNotFoundException('File not found or you do not have permission to view it.');
    }

    $fileExtension = pathinfo($file->getFile(), PATHINFO_EXTENSION);

    $isPdf = in_array($fileExtension, ['pdf']);
    $isImage = in_array($fileExtension, ['png', 'jpeg', 'jpg', 'gif', 'bmp', 'webp', 'svg', 'tiff']);
    $isVideo = in_array($fileExtension, ['mp4', 'avi', 'mov']);
    $isAudio = in_array($fileExtension, ['mp3', 'wav']);
    $isDocument = in_array($fileExtension, ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt']);
    

    return $this->render('file/view.html.twig', [
        'file' => $file,
        'isPdf' => $isPdf,
        'isImage' => $isImage,
        'isVideo' => $isVideo,
        'isAudio' => $isAudio,
        'isDocument' => $isDocument,
    ]);
}















}

templates/file/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fichiers{% endblock %}

{% block body %}
{% set GB_IN_BYTES = 1024 * 1024 * 1024 %}

<div class="container mt-5">

    <!-- Flash Messages -->
    {% for message in app.flashes('success') %}
        <div class="alert alert-success mb-3">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger mb-3">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('dropzone_success') %}
        <div class="alert alert-success mb-3" role="alert" data-turbo-cache="false">
            {{ message }}
        </div>
    {% endfor %}

    <!-- File Upload Card -->
    <div class="card shadow-sm">
        <div class="card-header bg-info text-white">
            Télécharger un fichier
        </div>
        <div class="card-body">
            {{ form_start(form, {'attr': {'class': 'form'}}) }}
            <div class="mb-3">
                {{ form_label(form.file, 'Fichier', {'label_attr': {'class': 'form-label'}}) }}
                {{ form_widget(form.file, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Télécharger</button>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-5">
        <h3>Vos fichiers :</h3>

        <!-- Space Information -->
        <div class="d-flex justify-content-between mb-4 mt-4">
            <p><strong>Espace utilisé:</strong> {{ (app.user.usedSpace * GB_IN_BYTES)|number_format(0, ',', '') }} Octets</p>
            <p><strong>Espace total disponible:</strong> {{ (app.user.totalSpace * GB_IN_BYTES)|number_format(0, ',', '') }} Octets</p>
            <p><strong>Espace restant:</strong> {{ ((app.user.totalSpace * GB_IN_BYTES) - (app.user.usedSpace * GB_IN_BYTES))|number_format(0, ',', '') }} Octets</p>
        </div>


    <!-- Progress Bar -->
        <div class="progress mb-4" style="height: 30px;">
            <div class="progress-bar" role="progressbar" style="width: {{ (app.user.usedSpace / app.user.totalSpace) * 100 }}%;" aria-valuenow="{{ (app.user.usedSpace / app.user.totalSpace) * 100 }}" aria-valuemin="0" aria-valuemax="100">
                {{ (app.user.usedSpace / app.user.totalSpace) * 100 | round(2) }}%
            </div>
        </div>


   <table class="table table-striped table-hover shadow-sm">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">
                <div class="row text-center">
                    <div class="col-md-9 offset-md-0">
                        <input type="text" class="form-control" id="fileSearchInput" placeholder="Tapez pour rechercher...">
                    </div>
                </div>
            </th>
            <th scope="col">
               

                <div class="row text-center">
                    <div class="col-md-11 offset-md-0">
                        <select class="form-control" id="fileTypeFilter">
                        <!-- Les options seront ajoutées dynamiquement par JavaScript -->
                        <option value="all">Les types &darr;</option>
                    </select>                    
                    </div>
                </div>


            </th>
            <th scope="col" class="text-center sortable"  id="sizeFileColumn">Taille (Octets) &darr;</th>
            <th scope="col" class="text-center sortable" id="dateAdded">Date d'ajout &darr;</th>
            <th scope="col" class="text-center">Visualiser</th>
            <th scope="col" class="text-center">Télécharger</th>
            <th scope="col" class="text-center">Supprimer</th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <th scope="row">{{ loop.index }}</th>
            <td>{{ file.name }}</td>
            <td class="text-center">
                {% set fileExtension = file.name|split('.')|last|lower %}
                {{ fileExtension }}
            </td>
            <td>{{ file.size }}</td>
            <td>{{ file.date|date('d/m/Y H:i') }}</td>
            <td class="text-center">
                <a href="{{ path('app_file_view', {'id': file.id}) }}" class="btn btn-info">Visualiser</a>
            </td >
            <td class="text-center">
                <a href="{{ path('file_download', {'id': file.id}) }}" class="btn btn-primary">Télécharger</a>
            </td>
            <td class="text-center">
                <form action="{{ path('file_delete', {'id': file.id}) }}" method="post" onsubmit="return confirmDelete();">
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
                <script>
                    function confirmDelete() {
                        return confirm("Êtes-vous sûr de vouloir supprimer ce fichier ?");
                    }
                </script>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>


<script>
    isAdmin = false;

    document.addEventListener("DOMContentLoaded", function() {
        const fileTypeFilter = document.getElementById('fileTypeFilter');
        const tableRows = document.querySelectorAll('table tbody tr');
        const fileTypes = new Set();

        tableRows.forEach(row => {
            const fileName = row.querySelector('td:nth-child(2)').textContent;
            const fileExtension = fileName.slice(((fileName.lastIndexOf(".") - 1) >>> 0) + 2).toLowerCase();

                fileTypes.add(fileExtension.toLowerCase());
        });

        fileTypes.forEach(type => {
            const option = document.createElement('option');
            option.value = type;
            option.textContent = type;
            fileTypeFilter.appendChild(option);
        });

        document.getElementById('fileSearchInput').addEventListener('input', filterFiles);
        fileTypeFilter.addEventListener('change', filterFiles);

        function filterFiles() {
            const searchTerm = document.getElementById('fileSearchInput').value.toLowerCase();
            const selectedType = fileTypeFilter.value;

            tableRows.forEach(row => {
                const fileName = row.querySelector('td:nth-child(2)').textContent.toLowerCase();
                const fileExtension = fileName.slice(((fileName.lastIndexOf(".") - 1) >>> 0) + 2);

                if ((fileName.includes(searchTerm) || searchTerm === "") && (fileExtension === selectedType || selectedType === "all")) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        }
    });

</script>
{% endblock %}

templates/file/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container mt-5">

    <!-- File Card -->
    <div class="card shadow-sm">
        
        <!-- Header -->
        <div class="card-header bg-info text-white d-flex justify-content-between align-items-center">
            {{ file.name }}
            <a href="{{ path('app_file') }}" class="btn btn-light">Retour</a>
        </div>

        <!-- Body -->
        <div class="card-body">
            {% if isPdf %}
                <embed src="{{ path('app_file_serve', {'filename': file.getFile}) }}" type="application/pdf" class="w-100" style="height:80vh;" />
            {% elseif isImage %}
                <img src="{{ path('app_file_serve', {'filename': file.getFile}) }}" alt="{{ file.name }}" class="img-fluid rounded shadow">
            {% elseif isVideo %}
                <video width="100%" controls>
                    <source src="{{ path('app_file_serve', {'filename': file.getFile}) }}" type="video/mp4">
                    Votre navigateur ne prend pas en charge les vidéos.
                </video>
            {% elseif isAudio %}
                <audio controls>
                    <source src="{{ path('app_file_serve', {'filename': file.getFile}) }}" type="audio/mp3">
                    Votre navigateur ne prend pas en charge l'audio.
                </audio>
            {% elseif isDocument %}
{% if isDocument %}
    <iframe src="https://view.officeapps.live.com/op/embed.aspx?src={{ absolute_url(path('app_file_serve', {'filename': file.getFile})) }}" class="w-100" style="height:80vh;"></iframe>
{% endif %}

            {% else %}
                <p>Ce format de fichier n'est pas pris en charge pour la visualisation.</p>
            {% endif %}
        </div>

        <!-- Footer -->
        <div class="card-footer d-flex justify-content-end">
            <a href="{{ path('file_delete', {'id': file.id}) }}" class="btn btn-danger" onclick="return confirm('Voulez-vous vraiment supprimer ce fichier?');">Supprimer</a>
        </div>

    </div>
</div>

{% endblock %}